variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - precompile
    - build
    - test

precompile:
    stage: precompile
    script: 
        - ./precompile_llvm.sh
    cache:
        key: precompile
        paths:
            - precompile_llvm
            - deps/llvm-project-prebuild/
            - precompile_llvm/
    only:
        - master
        - testing

build:
    stage: build
    dependencies: [precompile]
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j$(nproc)
        - cd ..
        - mkdir build_release
        - cd build_release
        - cmake ..
        - make -j$(nproc)
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
        policy: pull
    artifacts:
        paths:
            - ./build/tauc
            - ./build_release/tauc
        expire_in: 20 minutes
    only:
        - master
        - testing

test:
    stage: test
    dependencies: [build]
    script:
       - ./tests/run_all_tests.sh
        #TODO: make build path configurable in test scripts
       - mv ./build ./build_debug
       - mv ./build_release ./build 
       - ./tests/run_all_tests.sh
    only:
        - master
        - testing
