# Use the official gcc image
image: gcc

before_script:
    # Install build dependencies
    - apt-get update && apt-get -y install cmake

myapp:
    # Build the application
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make