#image: alpine

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - test

build:
    stage: build
#    before_script:
#        - apk update
#        - apk add gcc make cmake build-base
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug TAU_LLVM_PRECOMPILED=OFF ../
        - make -j$(nproc)
    artifacts:
        paths:
            - ./build
            - ./build/tauc
        expire_in: 20 minutes
    only:
        - master

test:
    stage: test
    script:
        - ./build/tauc
       # - valgrind --track-origins=yes --leak-check=full --error-exitcode=1 --suppressions test/valgrind_suppressions./build/tauc 
