variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - precompile
    - build
    - test

linux:precompile:
    stage: precompile
    needs: []
    tags: [g++, CMake, amd64, debian]
    script: 
        - ./precompile_llvm.sh
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
            - precompile_llvm/
    only:
        - master
        - testing

linux:build:debug:
    stage: build
    needs: ["linux:precompile"]
    tags: [g++, CMake, amd64, debian]
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j$(nproc)
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
        policy: pull
    artifacts:
        paths:
            - ./build/tauc
        expire_in: 20 minutes
    only:
        - master
        - testing


linux:build:release:
    stage: build
    needs: ["linux:precompile"]
    tags: [g++, CMake, amd64, debian]
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j$(nproc)
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
        policy: pull
    artifacts:
        paths:
            - ./build/tauc
        expire_in: 20 minutes
    only:
        - master
        - testing


linux:test:debug:
    stage: test
    needs: ["linux:build:debug"]
    tags: [g++, CMake, amd64, debian]
    script:
       - ./tests/run.sh
    only:
        - master
        - testing


linux:test:release:
    stage: test
    needs: ["linux:build:release"]
    tags: [g++, CMake, amd64, debian]
    script:
       - ./tests/run.sh
    only:
        - master
        - testing

linux:valgrind:debug:
    stage: test
    needs: ["linux:build:debug"]
    tags: [g++, CMake, amd64, debian]
    script:
       - ./tests/run.sh -v -s bigtest
    only:
        - master
        - testing


linux:valgrind:release:
    stage: test
    needs: ["linux:build:release"]
    tags: [g++, CMake, amd64, debian]
    script:
       - ./tests/run.sh -v -s bigtest
    only:
        - master
        - testing
