variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - precompile
    - build
    - test

precompile:
    stage: precompile
    script: 
        - git submodule init
        - git submodule update --recursive --remote
        - ./precompile_llvm.sh
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
    only:
        - master

build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
        - make -j$(nproc)
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
        policy: pull
    artifacts:
        paths:
            - ./build
            - ./build/tauc
        expire_in: 20 minutes
    only:
        - master

test:
    stage: test
    script:
        #run unit tests
        - ./build/tauc -U
        # test other output modes with at least one run :) 
        - ./build/tauc -L -S -E ./test/branchtest.t && ./a.out
        - ./build/tauc ./test/bigtest/footest.t && ./a.out
        - ./build/tauc ./test/multitest.t && ./a.out
        - ./build/tauc ./test/structtest.t && ./a.out
       # - valgrind --track-origins=yes --leak-check=full --error-exitcode=1 --suppressions test/valgrind_suppressions./build/tauc 
    only:
        - master
