image: alpine

stages:
    - build
    - test

build:
    stage: build
    before_script:
        - apk update
        - apk add gcc make cmake build-base
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
        - make
    artifacts:
        paths:
            - ./build
            - ./build/tauc
        expire_in: 20 minutes
    only:
        - master

test:
    stage: test
    script:
        - ./build/tauc
    only:
        - master
