variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - precompile
    - build
    - test

precompile:
    stage: precompile
    script: 
        - ./precompile_llvm.sh
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
    only:
        - master
        - testing

build:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
        - make -j$(nproc)
    cache:
        key: precompile
        paths:
            - deps/llvm-project-prebuild/
        policy: pull
    artifacts:
        paths:
            - ./build
            - ./build/tauc
        expire_in: 20 minutes
    only:
        - master
        - testing

test:
    stage: test
    script:
       - ./test/run_tests.sh
    only:
        - master
        - testing
